/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your hjh/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   hjh:
///    - family:  CustomIcons
///      hjh:
///       - asset: hjh/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData callLogo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shopBag = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconStar = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMapPin = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconLove = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconLocation = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconCancel = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconUp = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconSuccess = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconEdit = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMute = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconClose = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconYellowStar = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconNoColorStar = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconStarShine = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconIllustration = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconPath = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconCart = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconProfile = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconFilter = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconNotification = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconSearch = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconHome = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconChat = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMsgTwo = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMsg = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconTrash = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMinus = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconPlus = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMaps = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconVoucher = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconEditPen = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconLocationTwo = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData iconMessage = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logo = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
